name: Mobile PR Check

on:
  pull_request:
    branches: ["main"]
    paths:
      - "mobile/**"
      - "!mobile/**/*.md"

jobs:
  format_lint:
    name: Format & Lint (${{ github.head_ref }})
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Enable Corepack
        run: corepack enable

      - name: Install mobile dependencies
        run: yarn workspaces focus mobile --immutable

      - name: Format & Lint
        run: yarn workspace mobile format_lint:ci

  scan:
    name: Security Scan
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Secret scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --results=verified,unknown
